import { Department, EventItem, ProjectItem, BlogItem, HighlightItem, BoardPosition, BoardMember } from './types';

export const SOCIETY_INFO = {
  name: 'Civil Engineering Students Society',
  shortName: 'CESS UofK',
  fullName: 'Civil Engineering Students Society — University of Khartoum',
  foundedYear: 2013,
  email: 'lc.khartoum@gmail.com',
  phones: ['0117614433', '0913068350'],
  address: 'Department of Civil Engineering, Faculty of Engineering, University of Khartoum, Khartoum, Sudan',
  socialLinks: [
    { name: 'Facebook', url: '#' },
    { name: 'Instagram', url: '#' },
    { name: 'Twitter', url: '#' },
    { name: 'Telegram', url: '#' },
    { name: 'LinkedIn', url: '#' },
  ],
  mission:
    'Studying the current state of the university experience and comparing it with peer experiences in developed countries, and then trying to bridge the gap between the two by identifying deficiencies and working to provide solutions and maintaining them over the long term.',
  vision:
    'Provide a full-fledged university life experience for students of the Department of Civil Engineering at the University of Khartoum with a clear vision during study years to help students identify their destinations for the future.',
};

export const GOALS: string[] = [
  'To facilitate the task of the student in refining and improving the English language during his years of study.',
  'To raise awareness and to provide training opportunities for students according to selection mechanisms similar to global selection mechanisms.',
  'To provide scientific research opportunities for students in the various fields of civil engineering during summer vacation.',
  'To highlight opportunities for external participation of students and establish relationships with global associations to represent the university in various international forums.',
  'To spread the culture of academic councils, and exploiting them as a means of academic reform within a different level.',
];

export const STATS = [
  {
    value: '2013',
    label: 'ESTABLISHED',
    mechanism: 'Founded at the Department of Civil Engineering to enhance student development and academic reform.',
  },
  {
    value: '2',
    label: 'INTERNATIONAL AFFILIATIONS',
    mechanism: 'Sole IACES local committee in Sudan and official student chapter of ICE in the UK.',
  },
  {
    value: '4',
    label: 'SECTIONS',
    mechanism: 'Academic, Professional practice, Social and cultural, and Sports student bodies.',
  },
];

export const AFFILIATIONS = [
  {
    name: 'IACES LC Khartoum',
    title: 'International Association of Civil Engineering Students',
    desc: 'Sole local committee in Sudan, connecting Khartoum students with global exchange programs, international forums, and academic delegations.',
  },
  {
    name: 'ICE Student Chapter',
    title: 'Institution of Civil Engineers (UK)',
    desc: 'Official student chapter delivering professional practice guidelines, industry lectures, and chartered engineering pathways.',
  },
  {
    name: 'University of Khartoum',
    title: 'Faculty of Engineering',
    desc: 'Rooted in the department since 2013, collaborating with faculty leadership to provide long-term student academic resources.',
  },
];

export const DEPARTMENTS: Department[] = [
  {
    slug: 'academic',
    name: 'Academic',
    description: 'Academic aids, study resources and English-language support across the years of study.',
    objectives: [
      'Facilitate student development in technical and conversational English throughout study years.',
      'Maintain an active academic archive and exam preparation repository for all engineering batches.',
      'Sustain academic councils as a platform for collaborative reform and curriculum feedback.',
      'Organize peer review sessions and foundational tutoring for introductory engineering modules.',
    ],
    head: 'Head of Academic Section',
    email: 'academic.cess@uofk.edu',
    phone: '0117614433',
    slotLabel: 'LECTURE ROOM',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'professional-practice',
    name: 'Professional practice',
    description: 'Training, research placements and the routes into practice, including IACES and ICE participation.',
    objectives: [
      'Raise awareness and provide structured training opportunities aligned with international selection standards.',
      'Facilitate scientific research placements in civil engineering disciplines during summer vacation.',
      'Represent the university in international student forums and manage IACES exchange opportunities.',
      'Coordinate site inspections, field visits to major civil works, and technical industry lectures.',
    ],
    head: 'Head of Professional Practice Section',
    email: 'practice.cess@uofk.edu',
    phone: '0913068350',
    slotLabel: 'SITE VISIT — PILING RIG',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb18015f6?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'social-cultural',
    name: 'Social and cultural',
    description: 'Events, expeditions, conferences and the cultural life of the department.',
    objectives: [
      'Host the annual civil engineering student conference and technical seminars.',
      'Organize cultural gatherings, introductory welcome days for new students, and departmental expeditions.',
      'Maintain published society records, event documentations, and student editorial columns.',
      'Foster a tight-knit community among undergraduate batches, alumni, and departmental staff.',
    ],
    head: 'Head of Social and Cultural Section',
    email: 'social.cess@uofk.edu',
    phone: '0117614433',
    slotLabel: 'EVENING GATHERING',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'sports',
    name: 'Sports',
    description: 'Sport and recreation for Civil Engineering students across the faculty.',
    objectives: [
      'Coordinate faculty football, basketball, and table tennis tournaments.',
      'Field competitive civil engineering teams for university-wide inter-departmental leagues.',
      'Promote recreational athletic events, fitness sessions, and open participation activities.',
      'Support physical wellness alongside intensive academic curricula.',
    ],
    head: 'Head of Sports Section',
    email: 'sports.cess@uofk.edu',
    phone: '0913068350',
    slotLabel: 'STUDENTS OUTDOORS',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
  },
];

export const EVENTS: EventItem[] = [
  {
    slug: 'cesscon-3',
    name: 'CESSCON’3: 3rd Civil Engineering Students Society Conference & Exhibitions Week',
    kind: 'Conference & Exhibition',
    date: '7 Mar 2020 – 12 Mar 2020',
    regCloses: '5 Mar 2020',
    location: 'Prof. Al-Turabi Conference Hall & Central Campus, University of Khartoum',
    department: 'Academic',
    deptSlug: 'academic',
    status: 'Closed',
    summary: 'The 3rd biennial flagship conference and exhibitions week organized by CESS students with departmental professors, featuring 50 student engineering projects, 15 specialized lectures, and an official ministerial opening in Prof. Al-Turabi Hall with 500+ attendees.',
    content: [
      'The 3rd edition of the Civil Engineering Students Society conference and exhibitions week ("CESSCON’3") is a flagship biennial gathering organized inside the Department of Civil Engineering on the central campus of the University of Khartoum. The conference is planned and executed by student committees under the direct guidance of department professors, doctors, and lecturers.',
      'CESSCON’3 Exhibitions: Student researchers and engineers showcased civil engineering projects, physical structural models, and recent industry technologies. The exhibitions featured 27 projects and scale models in the academic tracks and 23 projects in the non-academic tracks, alongside contributions from external engineering firms.',
      'The Conference: Included 15 specialized lectures and workshops aiming to address contemporary global issues in civil engineering, obstacles hindering proper professional practice on the national level in Sudan, and practical solutions delivered by distinguished professors and specialized industry leaders.',
      'Official Opening Ceremony: On the 7th of March 2020, CESSCON’3 was officially opened in the Prof. Al-Turabi Conference Hall before an audience of over 500 students, teachers, and engineers. The ceremony was honoured by Minister of Higher Education Prof. Soughayroun, Minister of Infrastructure and Transportation Eng. Hashim Tahir, UofK Deputy Vice-Chancellor Dr. Kamal Eldin Eltayeb Yassin, UofK Academic Secretary Prof. Omran Fadl Osman, India to Sudan Deputy Ambassador Mr. Shakeel Ahmed, and the first Dean of the Faculty of Engineering Prof. Al-Turabi.',
    ],
    slotLabel: 'AUDITORIUM — CESSCON’3 CONFERENCE',
    image: '/images/cesscon-auditorium.jpg',
    gallery: [
      '/images/cesscon-auditorium.jpg',
      '/images/cesscon-ribbon.jpg',
      '/images/cesscon-speaker.jpg',
      '/images/cesscon-lecture.jpg',
    ],
  },
  {
    slug: 'icec-lc-khartoum',
    name: 'ICEC LC Khartoum: International Civil Engineering Competition (Local Elimination)',
    kind: 'Competition',
    date: '27 Feb 2020 – 10 Mar 2020',
    regCloses: '24 Feb 2020',
    location: 'Materials & Structural Testing Laboratories, Faculty of Engineering',
    department: 'Professional practice',
    deptSlug: 'professional-practice',
    status: 'Closed',
    summary: 'The Khartoum local committee edition of the prestigious IACES International Civil Engineering Competition, engaging 16 student teams across structural bridge model loading and advanced material mix design stages.',
    content: [
      'The International Civil Engineering Competition (ICEC) is a worldwide event organized by the International Association of Civil Engineering Students (IACES). Civil engineering students from across the globe compete in academic teams representing their home countries. The purpose is to foster international connection and technical excellence among future engineers.',
      'Local Competition Setup: A local edition was executed by IACES LC Khartoum at the University of Khartoum for civil engineering students in their 5th semester and above in teams of three. The local competition was structured into progressive elimination stages: Structures (16 Teams) → Materials (8 Teams) → Hydraulics (4 Teams) → Final Stage (2 Teams) → International Stage (scheduled for Belgrade, Serbia).',
      'Structures Stage (27/2/2020): In the first stage, each of the 16 participating teams designed and fabricated a 70×15×10 cm scale truss bridge model using wood sticks, hot glue guns, and rubber bands in 2 hours and 15 minutes. Models were subjected to incremental point loads until structural failure. Evaluation criteria scored loading resistance, aesthetic design, material economy, dimensional adherence, and time bonus points. 8 teams qualified.',
      'Materials Stage (10/3/2020): In the second stage, 8 qualifying teams constructed identical structures using custom combinations of wood, gypsum, cement, and small-diameter steel bars. Evaluated on load capacity, aesthetics, economy, and dimensional precision, with 4 teams qualifying for subsequent rounds before COVID-19 pandemic safety postponements.',
    ],
    slotLabel: 'TESTING LAB — TRUSS BRIDGE LOADING',
    image: '/images/icec-bridge.jpg',
    gallery: [
      '/images/icec-bridge.jpg',
      '/images/materials-lab.jpg',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    slug: 'ice-chartered-seminar',
    name: 'Getting Chartered Through ICE & Engineering Career Mentorship',
    kind: 'Seminar',
    date: '11 Mar 2020',
    regCloses: '9 Mar 2020',
    location: 'Al-Turabi Lectures Hall, University of Khartoum',
    department: 'Professional practice',
    deptSlug: 'professional-practice',
    status: 'Closed',
    summary: 'Specialized professional seminar presented by Eng. Abdelhafiz Abdelmoniem on Institution of Civil Engineers (ICE UK) student chapter benefits, chartered engineer pathways, and industry competencies.',
    content: [
      'As an official student chapter of the Institution of Civil Engineers (ICE) in the United Kingdom, CESS hosted this seminar during CESSCON’3 week to introduce undergraduates to global professional qualification routes.',
      'Eng. Abdelhafiz Abdelmoniem outlined the core competencies required for ICE professional review, continuing professional development (CPD) documentation, and transitioning from academic study to chartered engineering practice.',
      'Attendees participated in an open Q&A covering international engineering accreditation, structural ethics, and technical writing requirements for professional submissions.',
    ],
    slotLabel: 'LECTURE PODIUM — ICE CHARTERSHIP',
    image: '/images/cesscon-speaker.jpg',
    gallery: [
      '/images/cesscon-speaker.jpg',
      '/images/cesscon-auditorium.jpg',
      '/images/cesscon-lecture.jpg',
      'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    slug: 'traffic-congestion-lecture',
    name: 'Traffic Congestion in Khartoum State: Present Challenges & Future Solutions',
    kind: 'Technical Lecture',
    date: '8 Mar 2020',
    regCloses: '6 Mar 2020',
    location: 'Prof. Al-Turabi Conference Hall',
    department: 'Academic',
    deptSlug: 'academic',
    status: 'Closed',
    summary: 'Technical lecture presented by Dr. Majdi Mohamed Altaleb Zumrawi examining urban traffic flow, intersection bottlenecks, and roadway network planning in Khartoum state.',
    content: [
      'Delivered as part of the CESSCON’3 conference series, this lecture investigated the structural and management causes behind urban transportation bottlenecks across the greater Khartoum metropolitan area.',
      'Dr. Majdi Zumrawi analyzed volume-to-capacity ratios along major arterial corridors, signalized intersection delays, and public transit integration strategies.',
      'Students and attending practitioners examined geometric design modifications and regional bypass infrastructure proposals.',
    ],
    slotLabel: 'LECTURE HALL — TRANSPORTATION ENGINEERING',
    image: '/images/cesscon-lecture.jpg',
    gallery: [
      '/images/cesscon-lecture.jpg',
      '/images/cesscon-auditorium.jpg',
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=80',
      '/images/cesscon-speaker.jpg',
    ],
  },
  {
    slug: 'water-challenges-gerd',
    name: 'The Future & Challenges of Water in Sudan & Nile Basin Hydrology',
    kind: 'Seminar',
    date: '10 Mar 2020',
    regCloses: '8 Mar 2020',
    location: 'Al-Turabi Lectures Hall',
    department: 'Academic',
    deptSlug: 'academic',
    status: 'Closed',
    summary: 'Comprehensive scientific session presented by Prof. Abdeen Mohamed Ali Salih and Dr. Othman Altom Hamad on regional water resources, sewage system infrastructure, and Nile hydraulic dynamics.',
    content: [
      'This high-level seminar examined the strategic water challenges facing Sudan, focusing on municipal drainage systems, wastewater management in Khartoum state, and cross-border hydraulic dynamics along the Blue Nile basin.',
      'Prof. Abdeen Mohamed Ali Salih presented hydrological data on rainfall runoff models and sewer network rehabilitation needs.',
      'Dr. Othman Altom Hamad provided an in-depth technical breakdown of dam operation realities, sediment transport, and future water storage scenarios.',
    ],
    slotLabel: 'HYDROLOGY SEMINAR — NILE BASIN',
    image: '/images/cesscon-ribbon.jpg',
    gallery: [
      '/images/cesscon-ribbon.jpg',
      '/images/cesscon-lecture.jpg',
      'https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=1200&q=80',
      '/images/cesscon-auditorium.jpg',
    ],
  },
  {
    slug: 'academic-reforms-forum',
    name: 'Departmental Academic Reforms & Career Pathways (Naffaj Initiative)',
    kind: 'Student Forum',
    date: '9 Mar 2020',
    regCloses: '7 Mar 2020',
    location: 'Higher Education Hall, Faculty of Engineering',
    department: 'Academic',
    deptSlug: 'academic',
    status: 'Closed',
    summary: 'Interactive forum led by Eng. Aseel Mulla and student batch representatives exploring curriculum modernisation, soft skills cultivation, and engineering career readiness.',
    content: [
      'Focused on student empowerment and institutional dialogue, this forum examined methods for refining academic delivery, improving laboratory access, and integrating practical software tools into civil engineering coursework.',
      'The session featured the "Naffaj" initiative presentation on identifying post-graduation civil engineering career paths and aligning undergraduate electives with industry demands.',
      'Student representatives discussed actionable recommendations for academic council meetings and student-faculty collaboration.',
    ],
    slotLabel: 'STUDENT FORUM — ACADEMIC REFORMS',
    image: '/images/cesscon-speaker.jpg',
    gallery: [
      '/images/cesscon-speaker.jpg',
      '/images/cesscon-lecture.jpg',
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
      '/images/cesscon-ribbon.jpg',
    ],
  },
];

export const PROJECTS: ProjectItem[] = [
  {
    slug: 'course-hub',
    name: 'Course HUB: Integrated Engineering Learning & Career Platform',
    department: 'Academic',
    deptSlug: 'academic',
    status: 'Active',
    startDate: 'Jan 2025',
    endDate: 'Sep 2026',
    dateRange: 'Jan 2025 – Present (Phase 2 underway)',
    summary: 'A comprehensive educational program redefining the engineering learning experience from passive information reception to a complete professional career path, integrating technical skills, soft skills, and AI across Curated and Exclusive tracks.',
    content: [
      'Course HUB is an integrated educational program aiming to reshape the engineering learning journey, moving from mere "information reception" to "building a complete professional career pathway". It aggregates all educational tools in one platform organized into clear tracks connecting technical engineering competencies, soft skills, and artificial intelligence.',
      'Digital Learning Architecture: The platform relies on flexible digital learning to overcome traditional physical and scheduling constraints, providing a study environment that simulates actual job market demands. Course HUB is not a static repository, but a living educational entity continuously updated with emerging specializations.',
      'The Curated Path (المسار المنسق): Features a selection of the finest globally available free engineering courses, meticulously reviewed and vetted to save students time and effort in locating reliable, high-quality technical resources.',
      'The Exclusive Path (مسار الخبرة التطبيقية): Focuses on practical real-world execution and connecting coursework to actual engineering practice. Content is developed specifically by alumni and practitioner volunteers under senior supervision to transfer authentic field experience. This path covers advanced specializations not addressed in standard curricula, with verified completion certificates awarded upon successful module completion.',
      'Current Milestone: The program is currently advancing through Phase Two (Exclusive Practical Experience Path) towards comprehensive delivery.',
    ],
    slotLabel: 'DIGITAL PLATFORM — COURSE HUB GUIDE',
    image: '/images/coursehub-app.jpg',
    gallery: [
      '/images/coursehub-app.jpg',
      '/images/cesscon-lecture.jpg',
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    slug: 'cesscon-exhibitions',
    name: 'CESSCON’3 Biennial Engineering Exhibitions (27 Academic & 23 Non-Academic Projects)',
    department: 'Academic',
    deptSlug: 'academic',
    status: 'Completed',
    startDate: 'Nov 2019',
    endDate: 'Mar 2020',
    dateRange: 'Nov 2019 – Mar 2020',
    summary: 'Major departmental engineering exhibition showcasing 50 physical structural models, soil investigation displays, concrete mix innovations, and student prototypes in the central campus.',
    content: [
      'Organized as a cornerstone of CESSCON’3, the exhibitions provided civil engineering students with a premier venue to display graduation projects, scale physical prototypes, and industry technology applications.',
      'Academic Exhibitions: Encompassed 27 student projects spanning reinforced concrete design, foundation stability models, hydraulic flow flumes, and transportation highway alignments evaluated by an academic jury.',
      'Non-Academic & Industry Exhibitions: Featured 23 innovative student prototypes and interactive booths presenting modern construction materials, surveying technologies, and external corporate contributions.',
      'The exhibition was inaugurated during the opening ceremony by the Minister of Higher Education, Minister of Infrastructure, and university leadership, drawing hundreds of visitors across the five-day display.',
    ],
    slotLabel: 'ENGINEERING EXHIBITIONS — CESSCON’3',
    image: '/images/cesscon-ribbon.jpg',
    gallery: [
      '/images/cesscon-ribbon.jpg',
      '/images/cesscon-auditorium.jpg',
      '/images/icec-bridge.jpg',
      '/images/cesscon-lecture.jpg',
    ],
  },
  {
    slug: 'icec-local-championship',
    name: 'ICEC Local Bridge & Materials Engineering Championship',
    department: 'Professional practice',
    deptSlug: 'professional-practice',
    status: 'Completed',
    startDate: 'Feb 2020',
    endDate: 'Mar 2020',
    dateRange: 'Feb 2020 – Mar 2020',
    summary: 'Multi-stage engineering design and destructive load testing championship for 16 undergraduate teams in scaled structural trusses and composite material mixes under international IACES standards.',
    content: [
      'The ICEC Local Championship brought the International Civil Engineering Competition format to Khartoum, organizing four rigorous elimination stages in structural design, materials engineering, and hydraulics.',
      'Structures Stage: 16 teams competed to build 70×15×10 cm truss bridge models using wood sticks and glue guns, subjected to incremental failure loads in the department laboratory. 8 top-performing teams advanced.',
      'Materials Stage: 8 qualified teams constructed standardized structural elements with custom formulations of gypsum, cement, wood, and steel bars, evaluated on strength-to-weight ratio, finish aesthetics, and material economy.',
      'The championship established an annual benchmark for practical laboratory skills, teamwork, and structural intuition among Khartoum civil engineering undergraduates.',
    ],
    slotLabel: 'CHAMPIONSHIP — STRUCTURAL TESTING',
    image: '/images/icec-bridge.jpg',
    gallery: [
      '/images/icec-bridge.jpg',
      '/images/materials-lab.jpg',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    slug: 'resource-archive',
    name: 'Undergraduate Academic Resource & Exam Archive',
    department: 'Academic',
    deptSlug: 'academic',
    status: 'Active',
    startDate: 'Oct 2023',
    endDate: 'Ongoing',
    dateRange: 'Oct 2023 – Present',
    summary: 'A curated, multi-year repository of past examination papers, laboratory manuals, lecture slide decks, and solved tutorials across all study years.',
    content: [
      'The Undergraduate Academic Resource Archive is a continuous initiative by the Academic Section to compile, digitize, and categorize educational materials for every civil engineering subject.',
      'Materials are organized by academic year (First Year through Graduation Year) and subdivided into lectures, tutorials, lab sheets, and verified exam solutions reviewed by teaching assistants.',
      'The platform is updated at the conclusion of each examination cycle to ensure incoming cohorts have reliable, organized reference material.',
    ],
    slotLabel: 'ARCHIVE REPOSITORY — SCANNING & INDEXING',
    image: '/images/cesscon-lecture.jpg',
    gallery: [
      '/images/cesscon-lecture.jpg',
      '/images/cesscon-speaker.jpg',
      'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80',
      '/images/coursehub-app.jpg',
    ],
  },
];

export const BLOGS: BlogItem[] = [
  {
    slug: 'iaces-exchange-notes',
    title: 'Navigating International Student Exchanges as a Khartoum Civil Engineer',
    department: 'Professional practice',
    deptSlug: 'professional-practice',
    author: 'Executive Board · CESS',
    date: '18 Aug 2026',
    summary: 'Practical notes on preparing competitive application statements, technical portfolios, and English language credentials for IACES exchange programs.',
    content: [
      'International exchange opportunities offer civil engineering undergraduates firsthand exposure to alternative building standards, advanced seismic testing facilities, and diverse infrastructure planning cultures. As the sole local committee for IACES in Sudan, CESS LC Khartoum regularly coordinates with partner committees across the globe to identify placement slots for our students.',
      'Successful applicants typically distinguish themselves not merely through academic marks, but through clear articulate statements of purpose, active participation in departmental workshops, and demonstrated technical competency in standard engineering tools.',
      'When preparing your portfolio, focus on presenting laboratory reports with meticulous calculation clarity and well-annotated drawings. Ensure that all technical writing adheres to standard terminology and that your curriculum vitae accurately reflects your coursework competencies.',
      'The Professional Practice section conducts open advisory hours each semester to review draft statements and assist candidates through every phase of the international application timeline.',
    ],
    slotLabel: 'STUDENT DELEGATION — IACES COMMITTEE',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'reading-a-soil-report',
    title: 'Interpreting Geotechnical Site Reports: A Guide for Undergraduates',
    department: 'Academic',
    deptSlug: 'academic',
    author: 'Academic Committee · CESS',
    date: '10 Aug 2026',
    summary: 'A structured breakdown of borehole profiles, Atterberg limits, SPT N-values, and groundwater observations for structural design students.',
    content: [
      'Every civil engineering design begins with the ground beneath it. For students beginning coursework in foundation design and soil mechanics, an authentic geotechnical investigation report can initially appear dense with empirical charts and test borehole logs.',
      'The first section to examine is the regional geology summary and borehole stratigraphy log. Note the transition depths between surface fill, silty clays, dense sands, and bedrock refusal. In the Khartoum basin, special attention must always be given to expansive clay layers subject to seasonal moisture variations.',
      'Next, cross-reference standard penetration test (SPT) blow counts (N-values) with depth. Corrected N-values provide the foundation engineer with immediate empirical correlations for soil bearing capacity and permissible settlement criteria.',
      'Finally, inspect the groundwater table logs. The depth of the perched or permanent water table directly influences lateral earth pressures on basement walls, effective stress calculations, and dewatering specifications during construction.',
    ],
    slotLabel: 'LABORATORY TESTING — ATTERBERG LIMITS',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'annual-conference-notes',
    title: 'Highlights from the Annual Civil Engineering Conference Planning',
    department: 'Social and cultural',
    deptSlug: 'social-cultural',
    author: 'Organizing Committee · CESS',
    date: '28 Jul 2026',
    summary: 'Overview of selected keynote themes, undergraduate research panels, and logistical preparations for our upcoming departmental conference.',
    content: [
      'Preparations for the upcoming Annual Civil Engineering Students Conference are progressing across all four sections. This year’s technical sessions are structured around three primary pillars: resilient structural systems, sustainable geotechnical solutions, and modern construction management.',
      'The organizing committee has finalized the call for papers, inviting graduation project teams to submit extended abstracts for peer review by departmental faculty members.',
      'In addition to formal presentations, the conference floor will feature interactive exhibition booths from student clubs, software demonstration tables, and a dedicated career networking session connecting final-year students with practicing consulting engineers.',
    ],
    slotLabel: 'CONFERENCE PLANNING — COMMITTEE MEETING',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'how-the-council-works',
    title: 'Understanding Academic Councils and Student Representation',
    department: 'Academic',
    deptSlug: 'academic',
    author: 'Student Representatives · CESS',
    date: '15 Jul 2026',
    summary: 'Why academic councils matter for curriculum feedback, exam scheduling, and long-term departmental dialogue.',
    content: [
      'Academic councils represent one of the most effective institutional mechanisms for constructive dialogue between engineering students and faculty administration. Rooted in CESS Goal 5, our society actively promotes academic council forums to address issues of curriculum pacing, examination logistics, and laboratory access.',
      'Each academic year selects designated batch representatives who gather collective student feedback, analyze laboratory scheduling bottlenecks, and formulate structured proposals for faculty review.',
      'Through this collaborative process, the society has successfully coordinated adjusted tutorial schedules, improved computer lab availability, and secured additional study reference materials in the departmental library.',
      'Active student engagement in academic councils ensures that the civil engineering curriculum continues to evolve in response to the practical needs of the student body.',
    ],
    slotLabel: 'STUDENT FORUM — COUNCIL IN SESSION',
    image: 'https://images.unsplash.com/photo-1531497865144-0464ef8fb9a9?auto=format&fit=crop&w=1200&q=80',
  },
];

export const HIGHLIGHTS: HighlightItem[] = [
  {
    id: 'h1',
    date: '7 Mar 2020',
    title: 'CESSCON’3: 3rd Civil Engineering Students Society Conference & Exhibitions Week',
    summary: 'Over 500 attendees and 50 student projects inaugurated in Prof. Al-Turabi Hall with ministerial honours.',
    department: 'ACADEMIC',
    slug: 'cesscon-3',
    route: 'event',
  },
  {
    id: 'h2',
    date: 'Jan 2025',
    title: 'Course HUB: Integrated Engineering Learning & Career Platform',
    summary: 'Redefining civil engineering learning through Curated and Exclusive practical career tracks.',
    department: 'ACADEMIC',
    slug: 'course-hub',
    route: 'project',
  },
  {
    id: 'h3',
    date: '27 Feb 2020',
    title: 'ICEC LC Khartoum: International Civil Engineering Competition',
    summary: '16 teams competing in structural bridge load testing and materials formulation under IACES standards.',
    department: 'PROFESSIONAL PRACTICE',
    slug: 'icec-lc-khartoum',
    route: 'event',
  },
  {
    id: 'h4',
    date: '11 Mar 2020',
    title: 'Getting Chartered Through ICE & Engineering Career Mentorship',
    summary: 'Professional review and ICE UK student chapter pathways presented by Eng. Abdelhafiz Abdelmoniem.',
    department: 'PROFESSIONAL PRACTICE',
    slug: 'ice-chartered-seminar',
    route: 'event',
  },
];

export const BOARD_POSITIONS: BoardPosition[] = [
  {
    title: 'President',
    scope: 'Overall executive leadership, institutional representation, and society coordination with university administration.',
  },
  {
    title: 'Vice President',
    scope: 'Operational supervision, inter-departmental alignment, and strategic planning across all active committees.',
  },
  {
    title: 'Secretary',
    scope: 'Official correspondence, society records, documentation archives, and membership registers.',
  },
  {
    title: 'Treasurer',
    scope: 'Budgetary allocation, financial transparency, event expenditure tracking, and sponsorship accounting.',
  },
  {
    title: 'Head of Academic Section',
    scope: 'Supervision of academic archives, exam tutorials, language workshops, and academic council liaisons.',
  },
  {
    title: 'Head of Professional Practice Section',
    scope: 'Coordination of site visits, research opportunities, ICE student chapter affairs, and IACES LC Khartoum exchanges.',
  },
  {
    title: 'Head of Social and Cultural Section',
    scope: 'Planning and execution of the annual conference, cultural gatherings, expeditions, and editorial releases.',
  },
  {
    title: 'Head of Sports Section',
    scope: 'Organization of inter-departmental tournaments, faculty athletic leagues, and student recreational wellness.',
  },
];

export const BOARD_MEMBERS: BoardMember[] = [
  {
    id: 1,
    name: 'Musab Modawi',
    role: 'President',
    category: 'Executive',
    department: 'Presidency',
    scope: 'Overall executive leadership, institutional representation, and society coordination with faculty leadership.',
    image: '/images/board/musab-modawi.jpg',
  },
  {
    id: 2,
    name: 'Sohila Said',
    role: 'Vice President',
    category: 'Executive',
    department: 'Presidency',
    scope: 'Executive operational supervision, strategic planning, and inter-secretariat coordination.',
    image: '/images/board/Sohila.jpg',
  },
  {
    id: 3,
    name: 'Amna Ibrahim',
    role: 'Secretary-General',
    category: 'Executive',
    department: 'General Secretariat',
    scope: 'Official administrative governance, documentation archiving, and executive correspondence.',
  },
  {
    id: 4,
    name: 'Ola Abdelrahman',
    role: 'Academic Secretary',
    category: 'Secretariat',
    department: 'Academic',
    scope: 'Curriculum resources, student tutorial programs, examination archives, and academic reform initiatives.',
    image: '/images/board/ola.jpg',
  },
  {
    id: 5,
    name: 'Mosab Osman',
    role: 'Deputy Academic Secretary',
    category: 'Secretariat',
    department: 'Academic',
    scope: 'Academic workshop execution, study archive management, and undergraduate mentorship support.',
  },
  {
    id: 6,
    name: 'Mohammed Khogali',
    role: 'Deputy Academic Secretary',
    category: 'Secretariat',
    department: 'Academic',
    scope: 'Technical reference curation, academic tutorial coordination, and student study circles.',
  },
  {
    id: 7,
    name: 'Khallad Eltigani',
    role: 'Media Secretary',
    category: 'Secretariat',
    department: 'Media',
    scope: 'Society visual identity, digital publishing, media coverage, and communication campaigns.',
  },
  {
    id: 8,
    name: 'Raneem TagElsir',
    role: 'Deputy Media Secretary',
    category: 'Secretariat',
    department: 'Media',
    scope: 'Visual content design, event documentation, photographic archives, and social outreach.',
  },
  {
    id: 9,
    name: 'Dania Salah',
    role: 'Technical Secretary',
    category: 'Secretariat',
    department: 'Technical',
    scope: 'Engineering software workshops, technical training programs, and hands-on skill development.',
    image: '/images/board/Dania.jpg',
  },
  {
    id: 10,
    name: 'Alaa Abdalhalim',
    role: 'Deputy Technical Secretary',
    category: 'Secretariat',
    department: 'Technical',
    scope: 'Technical lab coordination, structural modelling tutorials, and software masterclasses.',
    image: '/images/board/alaa.jpg',
  },
  {
    id: 11,
    name: 'Ban Omer',
    role: 'Deputy Technical Secretary',
    category: 'Secretariat',
    department: 'Technical',
    scope: 'Engineering toolkit resources, computing sessions, and technical workflow guidance.',
  },
  {
    id: 12,
    name: 'Eisa Mustafa',
    role: 'Cultural Secretary',
    category: 'Secretariat',
    department: 'Cultural',
    scope: 'Cultural exhibitions, annual departmental conference programming, and community forums.',
    image: '/images/board/esaa.jpg',
  },
  {
    id: 13,
    name: 'Mohammed Ashraf',
    role: 'Deputy Cultural Secretary',
    category: 'Secretariat',
    department: 'Cultural',
    scope: 'Community activities, cultural seminars, student debates, and society gatherings.',
  },
  {
    id: 14,
    name: 'Mâab Salah',
    role: 'Financial Secretary',
    category: 'Executive',
    department: 'Finance',
    scope: 'Financial planning, budgetary oversight, sponsorship accounting, and resource allocation.',
  },
  {
    id: 15,
    name: 'Abubakr Abdelgadir',
    role: 'Deputy Financial Secretary',
    category: 'Executive',
    department: 'Finance',
    scope: 'Expenditure auditing, event budget tracking, and treasury documentation.',
  },
  {
    id: 16,
    name: 'Eithar Yousof',
    role: 'External Relations Secretary',
    category: 'Secretariat',
    department: 'External Relations',
    scope: 'IACES LC Khartoum international liaison, ICE UK chapter partnerships, and industry relations.',
  },
  {
    id: 17,
    name: 'Ryan Eltigani',
    role: 'Deputy External Relations Secretary',
    category: 'Secretariat',
    department: 'External Relations',
    scope: 'Global student exchange initiatives, institutional partnerships, and external delegations.',
  },
  {
    id: 18,
    name: 'Amen Ibrahim',
    role: 'Deputy External Relations Secretary',
    category: 'Secretariat',
    department: 'External Relations',
    scope: 'Industry site visit coordination, professional networks, and engineering guest seminars.',
    image: '/images/board/AMEN.jpg',
  },
  {
    id: 19,
    name: 'Ashraf Hashim',
    role: 'Sports Secretary',
    category: 'Secretariat',
    department: 'Sports',
    scope: 'Inter-departmental sporting tournaments, faculty leagues, and student athletic events.',
    image: '/images/board/ashrf.jpg',
  },
  {
    id: 20,
    name: 'Mohammed Atef',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, institutional legacy preservation, and strategic mentorship.',
  },
  {
    id: 21,
    name: 'Ahmed Tawfeek',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, society alumni liaison, and technical guidance.',
  },
  {
    id: 22,
    name: 'Abdelrahman Omer',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, academic counsel, and institutional continuity.',
  },
  {
    id: 23,
    name: 'Omer Bakri',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, professional development mentorship, and society guidance.',
  },
  {
    id: 24,
    name: 'Tawasoul Abubakar',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, external representation, and alumni engagement.',
  },
  {
    id: 25,
    name: 'MohammedelHabib Khalid',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, technical mentorship, and institutional stewardship.',
    image: '/images/board/MK.jpg',
  },
  {
    id: 26,
    name: 'Muzen Husham',
    role: 'Council Member',
    category: 'Council',
    department: 'Student Council',
    scope: 'Student body representation, legislative council deliberation, and policy governance.',
    image: '/images/board/Muzan.jpg',
  },
  {
    id: 27,
    name: 'Omar Ahmed',
    role: 'Council Member',
    category: 'Council',
    department: 'Student Council',
    scope: 'Student body representation, batch council oversight, and student advocacy.',
    image: '/images/board/omarAhmed.jpg',
  },
  {
    id: 28,
    name: 'Mohammed AbdelFattah',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, society advocacy, and engineering mentorship.',
    image: '/images/board/MAF.jpg',
  },
  {
    id: 29,
    name: 'Mazan Yaser',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, student initiative counsel, and departmental advisory.',
  },
  {
    id: 30,
    name: 'Mushataha Ahmed',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, project guidance, and institutional support.',
  },
  {
    id: 31,
    name: 'Aysha Abdelhalim',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, educational advocacy, and alumni network liaison.',
  },
  {
    id: 32,
    name: 'Abubakr Mohamed',
    role: 'Honorary Member',
    category: 'Honorary',
    department: 'Advisory',
    scope: 'Honorary advisory support, strategic society counsel, and student leadership mentorship.',
    image: '/images/board/abubaker.jpg',
  },
];